version: 2

project_name: zenget

before:
  hooks:
    - go mod verify
    - go mod tidy -diff

builds:
  - id: zenget
    main: .
    binary: zenget
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    flags:
      - -trimpath
    ldflags:
      - -s -w
    mod_timestamp: 0

archives:
  - id: zenget
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files: []

checksum:
  name_template: checksums.txt
  algorithm: sha256

changelog:
  sort: asc
